const mockDataFirstLetter = {
  meals: [
    {
      idMeal: '52978',
      strMeal: 'Kumpir',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Turkish',
      strInstructions: 'If you order kumpir in Turkey, the standard filling is first, lots of butter mashed into the potato, followed by cheese. There’s then a row of other toppings that you can just point at to your heart’s content – sweetcorn, olives, salami, coleslaw, Russian salad, allsorts – and you walk away with an over-stuffed potato because you got ever-excited by the choices on offer.\r\n\r\nGrate (roughly – you can use as much as you like) 150g of cheese.\r\nFinely chop one onion and one sweet red pepper.\r\nPut these ingredients into a large bowl with a good sprinkling of salt and pepper, chilli flakes (optional).',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg',
      strTags: 'SideDish',
      strYoutube: 'https://www.youtube.com/watch?v=IEDEtZ4UVtI',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Butter',
      strIngredient3: 'Cheese',
      strIngredient4: 'Onion',
      strIngredient5: 'Red Pepper',
      strIngredient6: 'Red Chile Flakes',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 large',
      strMeasure2: '2 tbs',
      strMeasure3: '150g',
      strMeasure4: '1 large',
      strMeasure5: '1 large',
      strMeasure6: 'Pinch',
      strMeasure7: ' ',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'http://www.turkeysforlife.com/2013/10/firinda-kumpir-turkish-street-food.html',
      dateModified: null,
    },
    {
      idMeal: '52971',
      strMeal: 'Kafteji',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Tunisian',
      strInstructions: 'Peel potatoes and cut into 5cm cubes.\r\nPour 1-2 cm of olive oil into a large pan and heat up very hot. Fry potatoes until golden brown for 20 minutes, turning from time to time. Place on kitchen paper to drain.\r\nCut the peppers in half and remove seeds. Rub a little olive oil on them and place the cut side down on a baking tray. Place them under the grill. Grill until the skin is dark and bubbly. While the peppers are still hot, put them into a plastic sandwich bag and seal it. Take them out after 15 minutes and remove skins.\r\nIn the meantime, heat more olive oil another pan. Peel the onions and cut into thin rings. Fry for 15 minutes until golden brown, turning them often. Add the Ras el hanout at the end.\r\nCut the pumpkin into 5cm cubes and fry in the same pan you used for the potatoes for 10-15 minutes until it is soft and slightly browned. Place on kitchen paper.\r\nPour the remaining olive oil out of the pan and put all the cooked vegetables into the pan and mix. Whisk eggs and pour them over the vegetables. Put the lid on the pan so that the eggs cook. Put the contents of the pan onto a large chopping board, add salt and pepper and chopped and mix everything with a big knife.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1bsv1q1560459826.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=-TFf-Zu-xQU',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Olive Oil',
      strIngredient3: 'Green Pepper',
      strIngredient4: 'Onions',
      strIngredient5: 'Ras el hanout',
      strIngredient6: 'Pumpkin',
      strIngredient7: 'Eggs',
      strIngredient8: 'Salt',
      strIngredient9: 'Pepper',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '5 Large',
      strMeasure2: '2 tbs',
      strMeasure3: '1',
      strMeasure4: '5',
      strMeasure5: '1 tbs',
      strMeasure6: '500g',
      strMeasure7: '24 Skinned',
      strMeasure8: 'Pinch',
      strMeasure9: 'Pinch',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'http://allrecipes.co.uk/recipe/12294/kafteji--tunisian-fried-vegetables-.aspx',
      dateModified: null,
    },
    {
      idMeal: '52769',
      strMeal: 'Kapsalon',
      strDrinkAlternate: null,
      strCategory: 'Lamb',
      strArea: 'Dutch',
      strInstructions: 'Cut the meat into strips. Heat oil in a pan and fry the strips for 6 minutes until it\'s ready.\r\nBake the fries until golden brown in a deep fryrer. When ready transfer to a backing dish. Make sure the fries are spread over the whole dish.\r\nCover the fries with a new layer of meat and spread evenly.\r\nAdd a layer of cheese over the meat. You can also use grated cheese. When done put in the oven for a few minutes until the cheese is melted.\r\nChop the lettuce, tomato and cucumber in small pieces and mix together. for a basic salad. As extra you can add olives jalapenos and a red union.\r\nDived the salad over the dish and Serve with garlicsauce and hot sauce',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sxysrt1468240488.jpg',
      strTags: 'Snack',
      strYoutube: 'https://www.youtube.com/watch?v=UIcuiU1kV8I',
      strIngredient1: 'Fries',
      strIngredient2: 'Doner Meat',
      strIngredient3: 'Garlic sauce',
      strIngredient4: 'Hotsauce',
      strIngredient5: 'Lettuce',
      strIngredient6: 'Tomato',
      strIngredient7: 'Cucumber',
      strIngredient8: 'Gouda cheese',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '250 Grams',
      strMeasure2: '500 Grams',
      strMeasure3: 'Topping',
      strMeasure4: 'Topping',
      strMeasure5: '1 Bulb',
      strMeasure6: '1',
      strMeasure7: '3rd',
      strMeasure8: '100 Grams',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      dateModified: null,
    },
    {
      idMeal: '52887',
      strMeal: 'Kedgeree',
      strDrinkAlternate: null,
      strCategory: 'Seafood',
      strArea: 'British',
      strInstructions: 'For the rice, heat the oil in a large, lidded pan, add the onion, then gently fry for 5 mins until softened but not coloured. Add the spices, season with salt, then continue to fry until the mix start to go brown and fragrant; about 3 mins.\r\nAdd the rice and stir in well. Add 600ml water, stir, then bring to the boil. Reduce to a simmer, then cover for 10 mins. Take off the heat and leave to stand, covered, for 10-15 mins more. The rice will be perfectly cooked if you do not lift the lid before the end of the cooking.\r\nMeanwhile, put the haddock and bay leaves in a frying pan, cover with the milk, then poach for 10 mins until the flesh flakes. Remove from the milk, peel away the skin, then flake the flesh into thumbsize pieces. Place the eggs in a pan, cover with water, bring to the boil, then reduce to a simmer. Leave for 4½-5 mins, plunge into cold water, then peel and cut the eggs into quarters. Gently mix the fish, eggs, parsley, coriander and rice together in the pan. Serve hot, sprinkled with a few extra herbs.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/utxqpt1511639216.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=_Pw1I1-SItE',
      strIngredient1: 'Smoked Haddock',
      strIngredient2: 'Bay Leaves',
      strIngredient3: 'Milk',
      strIngredient4: 'Eggs',
      strIngredient5: 'Parsley',
      strIngredient6: 'Coriander',
      strIngredient7: 'Vegetable Oil',
      strIngredient8: 'Onion',
      strIngredient9: 'Coriander',
      strIngredient10: 'Curry Powder',
      strIngredient11: 'Rice',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '300g',
      strMeasure2: '2',
      strMeasure3: '300ml ',
      strMeasure4: '4',
      strMeasure5: 'Handful',
      strMeasure6: 'Handful',
      strMeasure7: '2 tbs',
      strMeasure8: '1 chopped',
      strMeasure9: '1 tsp ',
      strMeasure10: '2 tsp',
      strMeasure11: '300g',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/10421/kedgeree',
      dateModified: null,
    },
  ],
};

module.exports = mockDataFirstLetter;
