export const SAVE_DRINKS = 'SAVE_DRINKS';
export const SAVE_MEALS = 'SAVE_MEALS';
export const SAVE_MEALS_CATEGORIES = 'SAVE_MEALS_CATEGORIES';
export const SAVE_DRINKS_CATEGORIES = 'SAVE_DRINKS_CATEGORIES';
